import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { SupportedLanguage } from '../types/interpreter';

interface AppLanguageContextType {
  appLang: SupportedLanguage;
  setAppLang: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const UI_DICTIONARY: Record<SupportedLanguage, Record<string, string>> = {
  es: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Modo de captura', freeMode: 'Modo Libre', manualMode: 'Manual', windowDuration: 'Duración', remaining: 'Restante', elapsed: 'Transcurrido',
    consecutive: 'Consecutivo',
    simultaneous: 'Simultáneo',
    facetoface: 'Cara a Cara',
    history: 'Historial',
    startListening: 'Iniciar Interpretación',
    stopListening: 'Finalizar Conversación',
    listeningBadge: 'EN VIVO',
    freeContinuous: 'Libre Continua',
    autoPauseLabel: 'Pausa automática tras voz clara:',
    active2s: 'Activo (1s)',
    disabled: 'Desactivado',
    clearSpeechOnly: 'Solo se interpreta voz clara al detectar una pausa.',
    pressRedButtonToStart: 'Pulsa el botón rojo para iniciar',
    accessingMic: 'Accediendo a micrófono...',
    interpretingGoogle: 'Interpretando con Google 3.5...',
    ready: 'Listo',
    sessionFinished: 'Sesión finalizada. Pulsa el botón rojo para iniciar.',
    consecutiveFreeBanner: 'Modo Consecutivo Libre · Conversación Continua',
    listeningStatus: '🎙️ Escuchando... (Pausa 1s para traducir y responder)',
    voiceDetected: 'Voz detectada',
    pauseDetected: 'Pausa detectada:',
    translationReadyTip: 'Traducción lista para reproducir al llegar a 1.0s',
    speakNaturallyTip: 'Habla con naturalidad · Pre-traducción palabra por palabra',
    libreContinuousTip: 'Modo Libre Continuo · Verde = Escuchando',
    realtimeSubtitles: 'Subtítulos en tiempo real',
    listen: 'Escuchar',
    copy: 'Copiar',
    export: 'Exportar',
    clearHistory: 'Limpiar historial',
    noHistory: 'No hay traducciones registradas aún.',
    noHistoryDesc: 'Realiza una interpretación consecutiva, simultánea o cara a cara para ver el registro aquí.',
    backToIntr: 'Volver al intérprete',
    translationLabel: 'Traducción:',
    originalLabel: 'Original',
    typeMessage: 'O escribe un texto para interpretar...',
    processing: 'Procesando...',
    play: 'Reproducir',
    stop: 'Detener',
    loading: 'Cargando...',
    simultaneousModeTitle: 'Modo Simultáneo (Continuo)',
    simultaneousReady: 'Streaming simultáneo listo',
    streamingActive: '● Streaming ininterrumpido activo (habla continuamente)',
    speakContinuouslyPrompt: 'Habla de corrido para ver la traducción inmediata continua...',
    typeSimultaneous: 'O escribe una frase simultánea...',
    holdToTalk: 'Mantener para hablar',
    releaseToSend: 'Soltar para enviar',
    counterpartAudio: 'Audio interlocutor',
    yourAudio: 'Tu audio',
    sessionLog: 'Registro de sesión',
    youUser: 'Tú (Usuario)',
    counterpart: 'Interlocutor',
    swapLanguages: 'Intercambiar idiomas',
  },
  en: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Capture mode', freeMode: 'Free', manualMode: 'Manual', windowDuration: 'Window', remaining: 'Remaining', elapsed: 'Elapsed',
    consecutive: 'Consecutive',
    simultaneous: 'Simultaneous',
    facetoface: 'Face to Face',
    history: 'History',
    startListening: 'Start Interpretation',
    stopListening: 'End Conversation',
    listeningBadge: 'LIVE',
    freeContinuous: 'Free Continuous',
    autoPauseLabel: '1s Auto-Pause with Pre-translation:',
    active2s: 'Active (1s)',
    disabled: 'Disabled',
    livePrecomputedBanner: 'Live Instant Translation (Pre-computed)',
    pressRedButtonToStart: 'Press the red button to start',
    accessingMic: 'Accessing microphone...',
    interpretingGoogle: 'Interpreting with Google 3.5...',
    ready: 'Ready',
    sessionFinished: 'Session ended. Press the red button to start.',
    consecutiveFreeBanner: 'Free Consecutive Mode · Continuous Conversation',
    listeningStatus: '🎙️ Listening... (Pause 1s to translate and reply)',
    pretranslating: 'Pre-translating on the fly...',
    pauseDetected: 'Pause detected:',
    translationReadyTip: 'Translation ready to play at 1.0s',
    speakNaturallyTip: 'Speak naturally · Word-by-word pre-translation',
    libreContinuousTip: 'Continuous Free Mode · Green = Listening',
    realtimeSubtitles: 'Real-time Subtitles',
    listen: 'Listen',
    copy: 'Copy',
    export: 'Export',
    clearHistory: 'Clear history',
    noHistory: 'No translations recorded yet.',
    noHistoryDesc: 'Perform an interpretation to see the log here.',
    backToIntr: 'Back to interpreter',
    translationLabel: 'Translation:',
    originalLabel: 'Original',
    typeMessage: 'Or type text to interpret...',
    processing: 'Processing...',
    play: 'Play',
    stop: 'Stop',
    loading: 'Loading...',
    simultaneousModeTitle: 'Simultaneous Mode (Continuous)',
    simultaneousReady: 'Simultaneous streaming ready',
    streamingActive: '● Uninterrupted streaming active (speak continuously)',
    speakContinuouslyPrompt: 'Speak continuously to see immediate ongoing translation...',
    typeSimultaneous: 'Or type a simultaneous phrase...',
    holdToTalk: 'Hold to talk',
    releaseToSend: 'Release to send',
    counterpartAudio: 'Interlocutor audio',
    yourAudio: 'Your audio',
    sessionLog: 'Session Log',
    youUser: 'You (User)',
    counterpart: 'Interlocutor',
    swapLanguages: 'Swap languages',
  },
  fr: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Mode de capture', freeMode: 'Libre', manualMode: 'Manuel', windowDuration: 'Durée', remaining: 'Restant', elapsed: 'Écoulé',
    consecutive: 'Consécutif',
    simultaneous: 'Simultané',
    facetoface: 'Face à Face',
    history: 'Historique',
    startListening: "Démarrer l'interprétation",
    stopListening: 'Terminer la conversation',
    listeningBadge: 'EN DIRECT',
    freeContinuous: 'Libre Continu',
    autoPauseLabel: 'Pause auto 1s avec pré-traduction :',
    active2s: 'Actif (1s)',
    disabled: 'Désactivé',
    livePrecomputedBanner: 'Traduction Instantanée en Direct (Pré-calculée)',
    pressRedButtonToStart: 'Appuyez sur le bouton rouge pour démarrer',
    accessingMic: 'Accès au microphone...',
    interpretingGoogle: 'Interprétation avec Google 3.5...',
    ready: 'Prêt',
    sessionFinished: 'Session terminée. Appuyez sur le bouton rouge pour démarrer.',
    consecutiveFreeBanner: 'Mode Consécutif Libre · Conversation Continue',
    listeningStatus: '🎙️ Écoute... (Pause 1s pour traduire et répondre)',
    pretranslating: 'Pré-traduction à la volée...',
    pauseDetected: 'Pause détectée :',
    translationReadyTip: 'Traduction prête à être lue à 1.0s',
    speakNaturallyTip: 'Parlez naturellement · Pré-traduction mot à mot',
    libreContinuousTip: 'Mode Libre Continu · Vert = Écoute',
    realtimeSubtitles: 'Sous-titres en temps réel',
    listen: 'Écouter',
    copy: 'Copier',
    export: 'Exporter',
    clearHistory: "Effacer l'historique",
    noHistory: 'Aucune traduction enregistrée.',
    noHistoryDesc: 'Effectuez une interprétation pour voir le journal ici.',
    backToIntr: "Retour à l'interprète",
    translationLabel: 'Traduction :',
    originalLabel: 'Original',
    typeMessage: 'Ou tapez du texte à interpréter...',
    processing: 'Traitement...',
    play: 'Écouter',
    stop: 'Arrêter',
    loading: 'Chargement...',
    simultaneousModeTitle: 'Mode Simultané (Continu)',
    simultaneousReady: 'Flux simultané prêt',
    streamingActive: '● Flux ininterrompu actif',
    speakContinuouslyPrompt: 'Parlez en continu pour voir la traduction...',
    typeSimultaneous: 'Ou tapez une phrase simultanée...',
    holdToTalk: 'Maintenir pour parler',
    releaseToSend: 'Relâcher pour envoyer',
    counterpartAudio: 'Audio interlocuteur',
    yourAudio: 'Votre audio',
    sessionLog: 'Journal de session',
    youUser: 'Vous (Utilisateur)',
    counterpart: 'Interlocuteur',
    swapLanguages: 'Échanger les langues',
  },
  pt: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Modo de captura', freeMode: 'Livre', manualMode: 'Manual', windowDuration: 'Duração', remaining: 'Restante', elapsed: 'Decorrido',
    consecutive: 'Consecutivo',
    simultaneous: 'Simultâneo',
    facetoface: 'Cara a Cara',
    history: 'Histórico',
    startListening: 'Iniciar Interpretação',
    stopListening: 'Encerrar Conversa',
    listeningBadge: 'AO VIVO',
    freeContinuous: 'Livre Contínuo',
    autoPauseLabel: 'Pausa auto 1s com pré-tradução:',
    active2s: 'Ativo (1s)',
    disabled: 'Desativado',
    livePrecomputedBanner: 'Tradução Instantânea ao Vivo (Pré-computada)',
    pressRedButtonToStart: 'Pressione o botão vermelho para iniciar',
    accessingMic: 'Acessando microfone...',
    interpretingGoogle: 'Interpretando com Google 3.5...',
    ready: 'Pronto',
    sessionFinished: 'Sessão encerrada. Pressione o botão vermelho para iniciar.',
    consecutiveFreeBanner: 'Modo Consecutivo Livre · Conversação Contínua',
    listeningStatus: '🎙️ Ouvindo... (Pausa 1s para traduzir e responder)',
    pretranslating: 'Pré-traduzindo em tempo real...',
    pauseDetected: 'Pausa detectada:',
    translationReadyTip: 'Tradução pronta para tocar em 1.0s',
    speakNaturallyTip: 'Fale com naturalidade · Pré-tradução palavra por palavra',
    libreContinuousTip: 'Modo Livre Contínuo · Verde = Ouvindo',
    realtimeSubtitles: 'Legendas em Tempo Real',
    listen: 'Ouvir',
    copy: 'Copiar',
    export: 'Exportar',
    clearHistory: 'Limpar histórico',
    noHistory: 'Nenhuma tradução registrada ainda.',
    noHistoryDesc: 'Realize uma interpretação para ver o registro aqui.',
    backToIntr: 'Voltar ao intérprete',
    translationLabel: 'Tradução:',
    originalLabel: 'Original',
    typeMessage: 'Ou digite texto para interpretar...',
    processing: 'Processando...',
    play: 'Reproduzir',
    stop: 'Parar',
    loading: 'Carregando...',
    simultaneousModeTitle: 'Modo Simultâneo (Contínuo)',
    simultaneousReady: 'Streaming simultâneo pronto',
    streamingActive: '● Streaming ininterrupto ativo',
    speakContinuouslyPrompt: 'Fale direto para ver a tradução...',
    typeSimultaneous: 'Ou digite uma frase simultânea...',
    holdToTalk: 'Manter para falar',
    releaseToSend: 'Soltar para enviar',
    counterpartAudio: 'Áudio interlocutor',
    yourAudio: 'Seu áudio',
    sessionLog: 'Registro de sessão',
    youUser: 'Você (Usuário)',
    counterpart: 'Interlocutor',
    swapLanguages: 'Inverter idiomas',
  },
  de: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Aufnahmemodus', freeMode: 'Frei', manualMode: 'Manuell', windowDuration: 'Zeitfenster', remaining: 'Verbleibend', elapsed: 'Vergangen',
    consecutive: 'Konsekutiv',
    simultaneous: 'Simultan',
    facetoface: 'Von Angesicht zu Angesicht',
    history: 'Verlauf',
    startListening: 'Interpretation starten',
    stopListening: 'Gespräch beenden',
    listeningBadge: 'LIVE',
    freeContinuous: 'Frei Kontinuierlich',
    autoPauseLabel: '1s Auto-Pause mit Vorübersetzung:',
    active2s: 'Aktiv (1s)',
    disabled: 'Deaktiviert',
    livePrecomputedBanner: 'Live-Sofortübersetzung (Vorausberechnet)',
    pressRedButtonToStart: 'Drücken Sie den roten Knopf zum Starten',
    accessingMic: 'Mikrofonzugriff...',
    interpretingGoogle: 'Interpretiere mit Google 3.5...',
    ready: 'Bereit',
    sessionFinished: 'Sitzung beendet. Drücken Sie den roten Knopf zum Starten.',
    consecutiveFreeBanner: 'Freier Konsekutivmodus · Kontinuierliches Gespräch',
    listeningStatus: '🎙️ Höre zu... (1s Pause zum Übersetzen)',
    pretranslating: 'Vorübersetzung im Gange...',
    pauseDetected: 'Pause erkannt:',
    translationReadyTip: 'Übersetzung bereit bei 1.0s',
    speakNaturallyTip: 'Natürlich sprechen · Wort-für-Wort-Vorübersetzung',
    libreContinuousTip: 'Kontinuierlicher Modus · Grün = Zuhören',
    realtimeSubtitles: 'Echtzeit-Untertitel',
    listen: 'Anhören',
    copy: 'Kopieren',
    export: 'Exportieren',
    clearHistory: 'Verlauf löschen',
    noHistory: 'Noch keine Übersetzungen.',
    noHistoryDesc: 'Führen Sie eine Interpretation durch.',
    backToIntr: 'Zurück zum Dolmetscher',
    translationLabel: 'Übersetzung:',
    originalLabel: 'Original',
    typeMessage: 'Oder Text eingeben...',
    processing: 'Wird verarbeitet...',
    play: 'Wiedergabe',
    stop: 'Stopp',
    loading: 'Laden...',
    simultaneousModeTitle: 'Simultanmodus (Kontinuierlich)',
    simultaneousReady: 'Simultanes Streaming bereit',
    streamingActive: '● Unterbrechungsfreies Streaming aktiv',
    speakContinuouslyPrompt: 'Sprechen Sie kontinuierlich...',
    typeSimultaneous: 'Oder Phrase eingeben...',
    holdToTalk: 'Halten zum Sprechen',
    releaseToSend: 'Loslassen zum Senden',
    counterpartAudio: 'Interlocutor-Audio',
    yourAudio: 'Ihr Audio',
    sessionLog: 'Sitzungsprotokoll',
    youUser: 'Sie (Benutzer)',
    counterpart: 'Interlocutor',
    swapLanguages: 'Sprachen tauschen',
  },
  ja: {
    appTitle: 'Klarity Polyglot',
    captureMode: '録音モード', freeMode: 'フリー', manualMode: '手動', windowDuration: '時間枠', remaining: '残り', elapsed: '経過',
    consecutive: '逐次通訳',
    simultaneous: '同時通訳',
    facetoface: '対面通訳',
    history: '履歴',
    startListening: '通訳を開始',
    stopListening: '会話を終了',
    listeningBadge: 'ライブ',
    freeContinuous: '自由連続',
    autoPauseLabel: '1秒自動一時停止（事前翻訳付き）:',
    active2s: '有効 (1秒)',
    disabled: '無効',
    livePrecomputedBanner: 'ライブ即時翻訳（事前計算済み）',
    pressRedButtonToStart: '赤いボタンを押して開始',
    accessingMic: 'マイクにアクセス中...',
    interpretingGoogle: 'Google 3.5で通訳中...',
    ready: '準備完了',
    sessionFinished: 'セッションが終了しました。赤いボタンを押して開始してください。',
    consecutiveFreeBanner: '自由逐次モード・連続会話',
    listeningStatus: '🎙️ 聴き取り中... (1秒の無音で翻訳)',
    pretranslating: '事前翻訳中...',
    pauseDetected: '無音検出:',
    translationReadyTip: '1.0秒で翻訳が再生準備完了',
    speakNaturallyTip: '自然に話してください・事前翻訳',
    libreContinuousTip: '自由連続モード・緑＝聴き取り中',
    realtimeSubtitles: 'リアルタイム字幕',
    listen: '聴く',
    copy: 'コピー',
    export: 'エクスポート',
    clearHistory: '履歴をクリア',
    noHistory: '履歴はありません。',
    noHistoryDesc: '通訳を行うとここに記録が表示されます。',
    backToIntr: '通訳に戻る',
    translationLabel: '翻訳:',
    originalLabel: '原文',
    typeMessage: 'テキストを入力...',
    processing: '処理中...',
    play: '再生',
    stop: '停止',
    loading: '読み込み中...',
    simultaneousModeTitle: '同時通訳モード（連続）',
    simultaneousReady: '同時ストリーミング準備完了',
    streamingActive: '● ストリーミング中',
    speakContinuouslyPrompt: '続けて話すと即座に翻訳されます...',
    typeSimultaneous: '同時通訳フレーズを入力...',
    holdToTalk: '長押しして話す',
    releaseToSend: '放して送信',
    counterpartAudio: '相手の音声',
    yourAudio: 'あなたの音声',
    sessionLog: 'セッションログ',
    youUser: 'あなた (ユーザー)',
    counterpart: '相手',
    swapLanguages: '言語を入れ替え',
  },
  zh: {
    appTitle: 'Klarity Polyglot',
    captureMode: '录音模式', freeMode: '自由模式', manualMode: '手动', windowDuration: '时长', remaining: '剩余', elapsed: '已用',
    consecutive: '交替传译',
    simultaneous: '同声传译',
    facetoface: '面对面',
    history: '历史记录',
    startListening: '开始口译',
    stopListening: '结束对话',
    listeningBadge: '直播',
    freeContinuous: '自由连续',
    autoPauseLabel: '1秒自动暂停（含预翻译）：',
    active2s: '激活 (1s)',
    disabled: '已禁用',
    livePrecomputedBanner: '实时即时翻译（预计算）',
    pressRedButtonToStart: '按下红色的按钮开始',
    accessingMic: '正在访问麦克风...',
    interpretingGoogle: '正在使用 Google 3.5 翻译...',
    ready: '就绪',
    sessionFinished: '会话已结束。按下红色的按钮开始。',
    consecutiveFreeBanner: '自由交替模式 · 连续对话',
    listeningStatus: '🎙️ 正在聆听... (停顿1秒自动翻译)',
    pretranslating: '实时预翻译中...',
    pauseDetected: '检测到停顿：',
    translationReadyTip: '1.0秒时即可瞬间播放翻译',
    speakNaturallyTip: '自然发言 · 实时预翻译',
    libreContinuousTip: '自由连续模式 · 绿色 = 正在聆听',
    realtimeSubtitles: '实时字幕',
    listen: '听',
    copy: '复制',
    export: '导出',
    clearHistory: '清除历史',
    noHistory: '暂无翻译记录。',
    noHistoryDesc: '进行口译后，记录将显示在此处。',
    backToIntr: '返回口译',
    translationLabel: '翻译：',
    originalLabel: '原文',
    typeMessage: '或输入要翻译的文本...',
    processing: '处理中...',
    play: '播放',
    stop: '停止',
    loading: '加载中...',
    simultaneousModeTitle: '同声传译模式（连续）',
    simultaneousReady: '同传流已就绪',
    streamingActive: '● 不间断同传中',
    speakContinuouslyPrompt: '保持连贯说话...',
    typeSimultaneous: '或输入同传短语...',
    holdToTalk: '按住说话',
    releaseToSend: '松开发送',
    counterpartAudio: '对方语音',
    yourAudio: '您的语音',
    sessionLog: '会话日志',
    youUser: '您 (用户)',
    counterpart: '对方',
    swapLanguages: '交换语言',
  },
  ar: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'وضع التسجيل', freeMode: 'حر', manualMode: 'يدوي', windowDuration: 'المدة', remaining: 'متبقي', elapsed: 'منقضي',
    consecutive: 'متتابع',
    simultaneous: 'فوري',
    facetoface: 'وجهاً لوجه',
    history: 'السجل',
    startListening: 'بدء الترجمة الفورية',
    stopListening: 'إنهاء المحادثة',
    listeningBadge: 'مباشر',
    freeContinuous: 'حر مستمر',
    autoPauseLabel: 'إيقاف مؤقت 1ث مع الترجمة المسبقة:',
    active2s: 'نشط (1ث)',
    disabled: 'معطل',
    livePrecomputedBanner: 'ترجمة فورية مباشرة (محسوبة مسبقاً)',
    pressRedButtonToStart: 'اضغط على الزر الأحمر للبدء',
    accessingMic: 'جاري الوصول للميكروفون...',
    interpretingGoogle: 'جاري الترجمة باستخدام Google 3.5...',
    ready: 'جاهز',
    sessionFinished: 'انتهت الجلسة. اضغط على الزر الأحمر للبدء.',
    consecutiveFreeBanner: 'وضع متتابع حر · محادثة مستمرة',
    listeningStatus: '🎙️ جاري الاستماع... (وقف 1ث للترجمة)',
    pretranslating: 'الترجمة المسبقة...',
    pauseDetected: 'تم اكتشاف وقفة:',
    translationReadyTip: 'الترجمة جاهزة للتشغيل عند 1.0ث',
    speakNaturallyTip: 'تكلم بشكل طبيعي · ترجمة مسبقة',
    libreContinuousTip: 'وضع حر مستمر · أخضر = استماع',
    realtimeSubtitles: 'الترجمة الفورية',
    listen: 'استماع',
    copy: 'نسخ',
    export: 'تصدير',
    clearHistory: 'مسح السجل',
    noHistory: 'لا توجد ترجمات مسجلة بعد.',
    noHistoryDesc: 'قم بإجراء ترجمة فورية لرؤية السجل هنا.',
    backToIntr: 'العودة للمترجم',
    translationLabel: 'الترجمة:',
    originalLabel: 'الأصلي',
    typeMessage: 'أو اكتب نصاً للترجمة...',
    processing: 'جاري المعالجة...',
    play: 'تشغيل',
    stop: 'إيقاف',
    loading: 'جاري التحميل...',
    simultaneousModeTitle: 'وضع الترجمة الفورية (مستمر)',
    simultaneousReady: 'البث الفوري جاهز',
    streamingActive: '● البث المستمر نشط',
    speakContinuouslyPrompt: 'تكلم باستمرار...',
    typeSimultaneous: 'أو اكتب عبارة فورية...',
    holdToTalk: 'اضغط للحديث',
    releaseToSend: 'اترك للإرسال',
    counterpartAudio: 'صوت الطرف الآخر',
    yourAudio: 'صوتك',
    sessionLog: 'سجل الجلسة',
    youUser: 'أنت (المستخدم)',
    counterpart: 'الطرف الآخر',
    swapLanguages: 'تبديل اللغات',
  },
  ko: {
    appTitle: 'Klarity Polyglot',
    captureMode: '녹음 모드', freeMode: '자유', manualMode: '수동', windowDuration: '시간', remaining: '남음', elapsed: '경과',
    consecutive: '순차 통역',
    simultaneous: '동시 통역',
    facetoface: '대면 통역',
    history: '기록',
    startListening: '통역 시작',
    stopListening: '대화 종료',
    listeningBadge: '실시간',
    freeContinuous: '자유 연속',
    autoPauseLabel: '1초 자동 일시정지 (사전 번역 포함):',
    active2s: '활성 (1s)',
    disabled: '비활성',
    livePrecomputedBanner: '실시간 즉시 번역 (사전 계산됨)',
    pressRedButtonToStart: '빨간색 버튼을 눌러 시작',
    accessingMic: '마이크 접근 중...',
    interpretingGoogle: 'Google 3.5로 통역 중...',
    ready: '준비됨',
    sessionFinished: '세션이 종료되었습니다. 빨간색 버튼을 눌러 시작하세요.',
    consecutiveFreeBanner: '자유 순차 모드 · 연속 대화',
    listeningStatus: '🎙️ 청취 중... (1초 침묵 시 번역)',
    pretranslating: '실시간 사전 번역 중...',
    pauseDetected: '침묵 감지:',
    translationReadyTip: '1.0초 시점에 즉시 재생 준비 완료',
    speakNaturallyTip: '자연스럽게 말하세요 · 사전 번역',
    libreContinuousTip: '자유 연속 모드 · 녹색 = 청취 중',
    realtimeSubtitles: '실시간 자막',
    listen: '듣기',
    copy: '복사',
    export: '내보내기',
    clearHistory: '기록 삭제',
    noHistory: '저장된 번역이 없습니다.',
    noHistoryDesc: '통역을 진행하면 여기에 기록이 표시됩니다.',
    backToIntr: '통역으로 돌아가기',
    translationLabel: '번역:',
    originalLabel: '원문',
    typeMessage: '번역할 텍스트 입력...',
    processing: '처리 중...',
    play: '재생',
    stop: '중지',
    loading: '로딩 중...',
    simultaneousModeTitle: '동시 통역 모드 (연속)',
    simultaneousReady: '동시 스트리밍 준비 완료',
    streamingActive: '● 실시간 스트리밍 활성',
    speakContinuouslyPrompt: '계속 말씀하세요...',
    typeSimultaneous: '동시 통역 문구 입력...',
    holdToTalk: '말하려면 누르세요',
    releaseToSend: '보내려면 놓으세요',
    counterpartAudio: '상대방 오디오',
    yourAudio: '내 오디오',
    sessionLog: '세션 로그',
    youUser: '나 (사용자)',
    counterpart: '상대방',
    swapLanguages: '언어 교환',
  },
  it: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Modalità acquisizione', freeMode: 'Libera', manualMode: 'Manuale', windowDuration: 'Durata', remaining: 'Rimanente', elapsed: 'Trascorso',
    consecutive: 'Consecutiva',
    simultaneous: 'Simultanea',
    facetoface: 'Faccia a Faccia',
    history: 'Cronologia',
    startListening: 'Avvia Interpretazione',
    stopListening: 'Termina Conversazione',
    listeningBadge: 'DAL VIVO',
    freeContinuous: 'Libera Continua',
    autoPauseLabel: 'Pausa auto 1s con pre-traduzione:',
    active2s: 'Attivo (1s)',
    disabled: 'Disattivato',
    livePrecomputedBanner: 'Traduzione Istantanea dal Vivo (Pre-computata)',
    pressRedButtonToStart: 'Premi il pulsante rosso per iniziare',
    accessingMic: 'Accesso al microfono...',
    interpretingGoogle: 'Interpretazione con Google 3.5...',
    ready: 'Pronto',
    sessionFinished: 'Sessione terminata. Premi il pulsante rosso per iniziare.',
    consecutiveFreeBanner: 'Modalità Consecutiva Libera · Conversazione Continua',
    listeningStatus: '🎙️ In ascolto... (Pausa 1s per tradurre)',
    pretranslating: 'Pre-traduzione in corso...',
    pauseDetected: 'Pausa rilevata:',
    translationReadyTip: 'Traduzione pronta per la riproduzione a 1.0s',
    speakNaturallyTip: 'Parla naturalmente · Pre-traduzione',
    libreContinuousTip: 'Modalità Libera Continua · Verde = In ascolto',
    realtimeSubtitles: 'Sottotitoli in tempo reale',
    listen: 'Ascolta',
    copy: 'Copia',
    export: 'Esporta',
    clearHistory: 'Cancella cronologia',
    noHistory: 'Nessuna traduzione registrata.',
    noHistoryDesc: 'Esegui un interpretariato per vedere il registro qui.',
    backToIntr: "Torna all'interprete",
    translationLabel: 'Traduzione:',
    originalLabel: 'Originale',
    typeMessage: 'O digita un testo da interpretare...',
    processing: 'Elaborazione...',
    play: 'Riproduci',
    stop: 'Ferma',
    loading: 'Caricamento...',
    simultaneousModeTitle: 'Modalità Simultanea (Continua)',
    simultaneousReady: 'Streaming simultaneo pronto',
    streamingActive: '● Streaming ininterrotto attivo',
    speakContinuouslyPrompt: 'Parla ininterrottamente...',
    typeSimultaneous: 'O digita una frase simultanea...',
    holdToTalk: 'Tieni premuto per parlare',
    releaseToSend: 'Rilascia per inviare',
    counterpartAudio: 'Audio interlocutore',
    yourAudio: 'Il tuo audio',
    sessionLog: 'Registro sessione',
    youUser: 'Tu (Utente)',
    counterpart: 'Interlocutore',
    swapLanguages: 'Inverti lingue',
  },
  ru: {
    appTitle: 'Klarity Polyglot',
    captureMode: 'Режим записи', freeMode: 'Свободный', manualMode: 'Ручной', windowDuration: 'Интервал', remaining: 'Осталось', elapsed: 'Прошло',
    consecutive: 'Последовательный',
    simultaneous: 'Синхронный',
    facetoface: 'Лицом к лицу',
    history: 'История',
    startListening: 'Начать перевод',
    stopListening: 'Завершить беседу',
    listeningBadge: 'ЭФИР',
    freeContinuous: 'Свободный непрерывный',
    autoPauseLabel: 'Автопауза 1с с предпереводом:',
    active2s: 'Активно (1с)',
    disabled: 'Отключено',
    livePrecomputedBanner: 'Мгновенный перевод в реальном времени',
    pressRedButtonToStart: 'Нажмите красную кнопку для старта',
    accessingMic: 'Доступ к микрофону...',
    interpretingGoogle: 'Перевод с помощью Google 3.5...',
    ready: 'Готово',
    sessionFinished: 'Сеанс завершен. Нажмите красную кнопку для старта.',
    consecutiveFreeBanner: 'Свободный последовательный режим · Непрерывная беседа',
    listeningStatus: '🎙️ Прослушивание... (Пауза 1с для перевода)',
    pretranslating: 'Предварительный перевод...',
    pauseDetected: 'Обнаружена пауза:',
    translationReadyTip: 'Перевод готов к воспроизведению на 1.0с',
    speakNaturallyTip: 'Говорите естественно · Предперевод',
    libreContinuousTip: 'Свободный непрерывный режим · Зеленый = Слушаю',
    realtimeSubtitles: 'Субтитры в реальном времени',
    listen: 'Слушать',
    copy: 'Копировать',
    export: 'Экспорт',
    clearHistory: 'Очистить историю',
    noHistory: 'История переводов пуста.',
    noHistoryDesc: 'Выполните перевод, чтобы увидеть запись здесь.',
    backToIntr: 'Назад к переводчику',
    translationLabel: 'Перевод:',
    originalLabel: 'Оригинал',
    typeMessage: 'Или введите текст для перевода...',
    processing: 'Обработка...',
    play: 'Воспроизвести',
    stop: 'Стоп',
    loading: 'Загрузка...',
    simultaneousModeTitle: 'Синхронный режим (Непрерывный)',
    simultaneousReady: 'Синхронный поток готов',
    streamingActive: '● Непрерывный поток активен',
    speakContinuouslyPrompt: 'Говорите непрерывно...',
    typeSimultaneous: 'Или введите синхронную фразу...',
    holdToTalk: 'Удерживайте для разговора',
    releaseToSend: 'Отпустите для отправки',
    counterpartAudio: 'Аудио собеседника',
    yourAudio: 'Ваше аудио',
    sessionLog: 'Журнал сеанса',
    youUser: 'Вы (Пользователь)',
    counterpart: 'Собеседник',
    swapLanguages: 'Поменять языки местами',
  },
};

const AppLanguageContext = createContext<AppLanguageContextType>({
  appLang: 'es',
  setAppLang: () => {},
  t: (key) => key,
});

export const AppLanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [appLang, setAppLang] = useState<SupportedLanguage>(() => {
    try {
      return (localStorage.getItem('polyglot_app_lang') as SupportedLanguage) || 'es';
    } catch {
      return 'es';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('polyglot_app_lang', appLang);
    } catch {}
  }, [appLang]);

  const t = (key: string): string => {
    const dict = UI_DICTIONARY[appLang] || UI_DICTIONARY['es'];
    return dict[key] || UI_DICTIONARY['es'][key] || key;
  };

  return (
    <AppLanguageContext.Provider value={{ appLang, setAppLang, t }}>
      {children}
    </AppLanguageContext.Provider>
  );
};

export const useAppLanguage = () => useContext(AppLanguageContext);
